<?php

use Illuminate\Database\Seeder;

class CmsLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cms_logs')->delete();
        
        \DB::table('cms_logs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 05:42:43',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ersaazis24m@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 05:46:10',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'cepy@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 3,
                'created_at' => '2019-11-07 05:46:25',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'cepy@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 3,
                'created_at' => '2019-11-07 06:26:26',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'cepy@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 3,
                'created_at' => '2019-11-07 06:34:17',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/edit-save/3',
                'description' => 'Memperbaharui data CEPY SLAMET pada Users Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>password</td><td>$2y$10$ZnhxRgqqCQAo4xLCFrgf4u7qJNi8lOMDL.2WUbhwloeCPCVxuRB.G</td><td></td></tr><tr><td>id_cms_privileges</td><td>2</td><td></td></tr><tr><td>status</td><td></td><td></td></tr><tr><td>tmpt_lahir</td><td></td><td>garut</td></tr><tr><td>url_schollar</td><td>https://scholar.google.co.id/citations?hl=id&user=pMg4mngAAAAJ&cstart=0&pagesize=999999999</td><td></td></tr><tr><td>url_dikti</td><td>https://forlap.ristekdikti.go.id/dosen/detail/Q0ZCQ0YxNTgtNjVDQi00MTE0LTlENUItMkZDRDczMUUzNzIw</td><td></td></tr><tr><td>nip</td><td></td><td>123</td></tr><tr><td>nidn</td><td></td><td>123</td></tr><tr><td>tanggal_lahir</td><td></td><td>2019-11-27</td></tr><tr><td>alamat</td><td></td><td></td></tr><tr><td>bidang_keahlian</td><td></td><td></td></tr><tr><td>id_dikti</td><td></td><td>asd</td></tr><tr><td>id_schollar</td><td></td><td>asd</td></tr><tr><td>id_scopus</td><td></td><td>asd</td></tr><tr><td>id_orchid</td><td></td><td>asd</td></tr></tbody></table>',
                'id_cms_users' => 3,
                'created_at' => '2019-11-07 06:43:22',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'cepy@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 3,
                'created_at' => '2019-11-07 06:48:01',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 06:48:26',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/delete/3',
                'description' => 'Menghapus data CEPY SLAMET pada Users Management',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 06:48:39',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ersaazis24m@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 06:49:39',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'cepy@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 4,
                'created_at' => '2019-11-07 06:49:47',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'cepy@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 4,
                'created_at' => '2019-11-07 06:50:35',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 06:50:44',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/delete/5',
                'description' => 'Menghapus data asdasd pada Users Management',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 06:51:13',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/delete/4',
                'description' => 'Menghapus data CEPY SLAMET pada Users Management',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 06:51:27',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 13:35:33',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ersaazis24m@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 17:37:47',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'eam24maret@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-07 17:56:01',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/forgot',
                'description' => 'Seseorang dengan IP 127.0.0.1 meminta password ulang eam24maret@gmail.com',
                'details' => '',
                'id_cms_users' => NULL,
                'created_at' => '2019-11-07 18:02:20',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'eam24maret@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-07 18:02:56',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'eam24maret@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-07 18:03:02',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/forgot',
                'description' => 'Seseorang dengan IP 127.0.0.1 meminta password ulang ersaazis24m@gmail.com',
                'details' => '',
                'id_cms_users' => NULL,
                'created_at' => '2019-11-07 18:49:02',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:49:47',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/edit-save/2',
                'description' => 'Memperbaharui data Ersa Azis Mansyur pada Users Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>password</td><td>$2y$10$DOyNIQExGbIh.MiqZhU4we5iwKWlMfUs4FeomZwkXxIrF6aRisDn6</td><td>$2y$10$9JhP0DMZjMIfC8Dwt.MDUO/Qy67b6xcoVLu4c0iQAzWrbYsk4Vjdy</td></tr><tr><td>id_cms_privileges</td><td>3</td><td></td></tr><tr><td>proses_update</td><td>1</td><td></td></tr><tr><td>auto_update</td><td>0</td><td></td></tr></tbody></table>',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:50:14',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/delete/6',
                'description' => 'Menghapus data CEPY SLAMET pada Users Management',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:51:46',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ersaazis24m@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:52:34',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ali@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 7,
                'created_at' => '2019-11-07 18:52:42',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ali@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 7,
                'created_at' => '2019-11-07 18:53:26',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:53:35',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/kategori_dokumen/add-save',
                'description' => 'Tambah data baru Bahan Ajar pada Kategori Dokumen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:56:24',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/kategori_dokumen/add-save',
                'description' => 'Tambah data baru Sertidikat pada Kategori Dokumen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:56:35',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/kategori_dokumen/add-save',
                'description' => 'Tambah data baru HKI pada Kategori Dokumen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:56:41',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/kategori_dokumen/add-save',
                'description' => 'Tambah data baru Silabus pada Kategori Dokumen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:56:49',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/kategori_dokumen/add-save',
                'description' => 'Tambah data baru RPS pada Kategori Dokumen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:56:52',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/kategori_dokumen/add-save',
                'description' => 'Tambah data baru Surat Tugas pada Kategori Dokumen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:56:59',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/kategori_dokumen/add-save',
                'description' => 'Tambah data baru Artikel pada Kategori Dokumen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:57:10',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/kategori_dokumen/add-save',
                'description' => 'Tambah data baru Jurnal pada Kategori Dokumen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:57:14',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/kategori_dokumen/edit-save/2',
                'description' => 'Memperbaharui data Sertifikat pada Kategori Dokumen',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>nama</td><td>Sertidikat</td><td>Sertifikat</td></tr></tbody></table>',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 18:57:26',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ersaazis24m@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 19:10:23',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ali@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 7,
                'created_at' => '2019-11-07 19:10:38',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ali@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 7,
                'created_at' => '2019-11-07 19:17:56',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-07 19:18:07',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 10:07:29',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/dokumen_dosen/add-save',
                'description' => 'Tambah data baru Materi Satu pada Dokumen Dosen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 10:10:07',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/dokumen_dosen/add-save',
                'description' => 'Tambah data baru Materi Dua pada Dokumen Dosen',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 10:10:23',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ersaazis24m@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 11:13:06',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/forgot',
                'description' => 'Seseorang dengan IP 127.0.0.1 meminta password ulang ersaazis24m@gmail.com',
                'details' => '',
                'id_cms_users' => NULL,
                'created_at' => '2019-11-24 11:14:11',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 11:54:02',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/edit-save/2',
                'description' => 'Memperbaharui data Ersa Azis Mansyur pada Users Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>password</td><td>$2y$10$Jjn98U7pcaM6/o2viuTE2.ZJw1NSIQ0wxeDamZZzJ6Wo4mMXVbia2</td><td>$2y$10$WBu2OCWv0Mc9FyaWLDI32e1rSnVwPCaPKeLZYpeP.oyjtpcARHRkC</td></tr><tr><td>id_cms_privileges</td><td>3</td><td></td></tr><tr><td>proses_update</td><td>1</td><td></td></tr><tr><td>auto_update</td><td>0</td><td></td></tr></tbody></table>',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 11:54:16',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ersaazis24m@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 12:21:36',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ali@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 7,
                'created_at' => '2019-11-24 12:22:34',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ali@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 7,
                'created_at' => '2019-11-24 13:44:08',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 13:44:28',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/edit-save/1',
                'description' => 'Memperbaharui data Super Admin pada Users Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>password</td><td>$2y$10$bpUffL1n/316.B.QxAoZZeebvfjAU.LkYb3vkLTk6Ajd3w2mC8Psm</td><td>$2y$10$yOH214H4KlY5EFUlSSFwNuQMNa2fceQ0Y2i3uD5xEEw4dZ43mIZjW</td></tr><tr><td>status</td><td>Active</td><td></td></tr><tr><td>auto_update</td><td>0</td><td></td></tr></tbody></table>',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 13:44:43',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ersaazis24m@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 13:45:33',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'eam24maret@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:45:50',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Ilmu Hukum pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:51:39',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Ekonomi Syari’ah pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:51:54',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Religious Studies pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:52:07',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Pendidikan Agama Islam pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:52:17',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
            'description' => 'Tambah data baru Hukum Keluarga (AS) pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:52:27',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Manajemen Pendidikan Islam pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:52:35',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Komunikasi dan Penyiaran Islam pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:52:45',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Al-Qur’an dan Tafsir pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:52:51',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Al-Hadits pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:52:58',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Pendidikan Bahasa Arab pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:53:04',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Hukum Ekonomi Syari’ah pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:53:11',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/programstudi/add-save',
                'description' => 'Tambah data baru Sejarah Kebudayaan Islam pada Program Studi',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:53:18',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'eam24maret@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:53:35',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 13:53:53',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'ersaazis24m@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 13:55:34',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'eam24maret@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:55:48',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/8',
                'description' => 'Memperbaharui data Program Studi pada Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>color</td><td></td><td>normal</td></tr><tr><td>sorting</td><td>7</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 13:56:03',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/edit-save/7',
                'description' => 'Memperbaharui data MUHAMMAD ALI RAMDHANI pada Users Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>password</td><td>$2y$10$ZnhxRgqqCQAo4xLCFrgf4u7qJNi8lOMDL.2WUbhwloeCPCVxuRB.G</td><td></td></tr><tr><td>status</td><td></td><td></td></tr><tr><td>jenis_kelamin</td><td>Laki-Laki</td><td></td></tr><tr><td>tmpt_lahir</td><td></td><td></td></tr><tr><td>namapt</td><td>Universitas Islam Negeri Sunan Gunung Djati</td><td></td></tr><tr><td>namaprodi</td><td>Teknik Informatika</td><td></td></tr><tr><td>statuskeaktifan</td><td>Aktif</td><td></td></tr><tr><td>pend_tinggi</td><td>S3</td><td></td></tr><tr><td>fungsional</td><td>Profesor</td><td></td></tr><tr><td>ikatankerja</td><td>Dosen Tetap</td><td></td></tr><tr><td>proses_update</td><td>0</td><td></td></tr><tr><td>auto_update</td><td>0</td><td></td></tr><tr><td>url_schollar</td><td>https://scholar.google.co.id/citations?hl=id&user=zIeiRpMAAAAJ&cstart=0&pagesize=999999999</td><td>https://scholar.google.co.id/citations?user=zIeiRpMAAAAJ</td></tr><tr><td>nip</td><td></td><td></td></tr><tr><td>nidn</td><td></td><td></td></tr><tr><td>tanggal_lahir</td><td></td><td></td></tr><tr><td>alamat</td><td></td><td></td></tr><tr><td>bidang_keahlian</td><td></td><td></td></tr><tr><td>id_scopus</td><td></td><td></td></tr><tr><td>id_orchid</td><td></td><td></td></tr><tr><td>programstudi_id</td><td></td><td>12</td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 14:02:13',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'eam24maret@gmail.com keluar',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2019-11-24 14:18:32',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'ersaazis24m@gmail.com login dengan IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2019-11-24 14:18:43',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}